version: "3.8"

services:
  java-service:
    image: absinchiguano/analyti-java:latest
    build:
      context: ./java-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:   jdbc:postgresql://dpg-d28om7vdiees73f6af50-a.oregon-postgres.render.com:5432/analitycore_jrmo
      SPRING_DATASOURCE_USERNAME: analitycore
      SPRING_DATASOURCE_PASSWORD: HCu68VFH8YirGUJsSqZ3nQFu2HZEixuJ
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  python-service:
    image: absinchiguano/analyti-python:latest
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - java-service
    environment:
      DB_HOST:     dpg-d28om7vdiees73f6af50-a.oregon-postgres.render.com
      DB_PORT:     "5432"
      DB_NAME:     analitycore_jrmo
      DB_USER:     analitycore
      DB_PASSWORD: HCu68VFH8YirGUJsSqZ3nQFu2HZEixuJ
      ANALYSIS_URL: http://java-service:8080

  frontend:
    image: absinchiguano/analyti-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - python-service
