version: "3.8"

services:
  java-service:
    image: absinchiguano/analyti-java:latest
    build:
      context: ./java-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: postgresql://analitycore_c8jd_user:IIvaYhuEQQ0gG9K9JXykj8bbYhSjTTOw@dpg-d292lu2li9vc739em7ig-a/analitycore_c8jd
      SPRING_DATASOURCE_USERNAME: analitycore_c8jd
      SPRING_DATASOURCE_PASSWORD: IIvaYhuEQQ0gG9K9JXykj8bbYhSjTTOw
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  python-service:
    image: absinchiguano/analyti-python:latest
    build:
      context: ./python-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - java-service
    environment:
      DB_HOST:     dpg-d292lu2li9vc739em7ig-a
      DB_PORT:     "5432"
      DB_NAME:     analitycore_c8jd
      DB_USER:     analitycore_c8jd_user
      DB_PASSWORD: IIvaYhuEQQ0gG9K9JXykj8bbYhSjTTOw
      ANALYSIS_URL: http://java-service:8080

  frontend:
    image: absinchiguano/analyti-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - python-service
